apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+):(.+)
            replacement: $1:$2
      - job_name: 'order-processor'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['order-processor-service:8090']
      - job_name: 'rabbitmq'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['rabbitmq-service:15672']
      - job_name: 'redis'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['redis:6379']
      - job_name: 'mongodb'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['mongodb-service:27017']